# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg_login', '0002_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_user_id', models.ManyToManyField(related_name='joined_trips', to='reg_login.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_login.User')),
            ],
        ),
    ]
